import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/layout/header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className="min-h-screen bg-zinc-900 font-sans antialiased">
        <Header></Header>
        <main>{children}</main>
      </body>
    </html>
  );
}
